---
- hosts: localhost
  tasks:
    - name: Check if previous_inventory.json exists
      stat:
        path: /etc/previous_inventory.json
      register: previous_inventory_file

    - name: Create previous_inventory.json if it doesn't exist
      file:
        path: /etc/previous_inventory.json
        state: touch
      when: not previous_inventory_file.stat.exists

    - name: Fetch current inventory
      uri:
        url: "https://controller-443-omslkrgqpwll.env.play.instruqt.com/api/v2/inventories/2/"
        user: "admin"
        password: "ansible123!"
        force_basic_auth: yes
        return_content: yes
      register: current_inventory

    - name: Read previous inventory from file
      shell: cat /etc/previous_inventory.json
      register: previous_inventory

    - name: Compare current and previous inventory
      debug:
        msg: "Inventory has changed"
      when: current_inventory.content != previous_inventory.stdout
      
    - name: Save current inventory to file
      shell: echo '{{ current_inventory.content | from_json }}' > /etc/previous_inventory.json
      when: (current_inventory.content | from_json) == (previous_inventory.stdout | from_json)