---
- hosts: localhost
  gather_facts: no
  vars:
    ip_to_check: "192.168.1.1"  # The IP address to check
    inventory:  # The inventory
      - name: "host1"
        ip: "172.34.2.0"
        group: "web"
      - name: "host2"
        ip: "192.168.1.1"
        group: "web"
      - name: "host3"
        ip: "192.168.255.0"
        group: "data"
  tasks:
    - name: Check if IP address is in inventory
      debug:
        msg: "The IP address {{ ip_to_check }} is in the inventory."
      when: ip_to_check in (host.ip for host in inventory)

    - name: Print inventory
      debug:
        var: inventory