---
- hosts: localhost
  gather_facts: no
  vars:
    controller_url: "https://controller-443-ygqo5kmkth9i.env.play.instruqt.com/"
    username: "admin"
    password: "ansible123!"
  tasks:
    - name: Retrieve inventories
      uri:
        url: "{{ controller_url }}/api/v2/inventories/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
      register: inventories

    - name: Print inventories
      debug:
        var: inventories.json.results