---
- hosts: localhost
  gather_facts: no
  collections:
    - awx.awx
  tasks:
    - name: Set ANSIBLE_COLLECTIONS_PATHS environment variable
      ansible.builtin.set_fact:
        ansible_env:
          ANSIBLE_COLLECTIONS_PATHS: "/runner/requirements_collections/ansible_collections"
    - name: Check if previous_inventory.json exists
      stat:
        path: /etc/previous_inventory.json
      register: previous_inventory_file

    - name: Create previous_inventory.json if it doesn't exist
      file:
        path: /etc/previous_inventory.json
        state: touch
      when: not previous_inventory_file.stat.exists
    - name: Print ANSIBLE_COLLECTIONS_PATHS
      debug:
        msg: "{{ ansible_env.ANSIBLE_COLLECTIONS_PATHS }}"
        
    - name: Add hosts to inventory
      awx.awx.tower_host:
        name: "testhost"
        description: "rhel host"
        inventory: "rhel inventory"
        state: present
        enabled: true
        tower_host: "https://controller-443-omslkrgqpwll.env.play.instruqt.com"
        tower_username: "admin"
        tower_password: "ansible123!"
        tower_verify_ssl: false

    - name: Read previous inventory from file
      shell: cat /etc/previous_inventory.json
      register: previous_inventory

    - name: Compare current and previous inventory
      fail:
        msg: "Inventory has changed"
      when: current_inventory.stdout != previous_inventory.stdout