---
- hosts: localhost
  tasks:
    - name: Check if previous_inventory.json exists
      stat:
        path: /etc/previous_inventory.json
      register: previous_inventory_file

    - name: Create previous_inventory.json if it doesn't exist
      file:
        path: /etc/previous_inventory.json
        state: touch
      when: not previous_inventory_file.stat.exists

    - name: Fetch current inventory
      tower_inventory:
        name: "rhel inventory"
        organization: "Default"
        controller_host: "https://localhost"
        controller_username: "admin"
        controller_password: "ansible123!"
      register: current_inventory

    - name: Read previous inventory from file
      shell: cat /etc/previous_inventory.json
      register: previous_inventory

    - name: Compare current and previous inventory
      fail:
        msg: "Inventory has changed"
      when: current_inventory.stdout != previous_inventory.stdout

    - name: Save current inventory to file
      shell: echo '{{ current_inventory.stdout }}' > /etc/previous_inventory.json
      when: current_inventory.stdout == previous_inventory.stdout