---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    access_key: 'AKIAUH5VZX6A5OUAOLGL'
    secret_key: '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'
    region: 'us-west-2'
    image_id: 'ami-093467ec28ae4fe03'
    instance_type: 't2.micro'
    keypair: 'key2'
    security_group: 'sg-00313b4b6df41fe83'
  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        security_group: "{{ security_group }}"
        wait: yes
        count: 1