---
- name: build report with facts
  hosts: ec2-34-222-48-92.us-west-2.compute.amazonaws.com
  gather_facts: true

  tasks:
    - name: load retrieve info role
      import_playbook: retrieve_info.yml
    - name: deploy report
      import_playbook: deploy_report.yml