---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    region: 'us-west-2'
    image_id: 'ami-093467ec28ae4fe03'
    instance_type: 't2.micro'
    keypair: 'first_key'
    security_group: 'sg-00313b4b6df41fe83'
  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        security_groups: "{{ security_group }}"
        wait: yes
        count: 1