---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    access_key: 'YOUR_ACCESS_KEY'
    secret_key: 'YOUR_SECRET_KEY'
    region: 'us-west-2'
    image: 'ami-0c55b159cbfafe1f0'
    instance_type: 't2.micro'
    keypair: 'your-keypair'
    security_group: 'sg-0abcd1234efgh5678'
  tasks:
    - name: Launch instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        group_id: "{{ security_group }}"
        wait: yes
        count: 1