---
- name: Deploy Jinja2 template
  hosts: ec2-34-219-62-150.us-west-2.compute.amazonaws.com
  tasks:
    - name: Apply Jinja2 template
      template:
        src: helloworld.j2
        dest: /var/www/html/index.html