---
- name: Install Apache on EC2
  hosts: ec2-34-222-48-92.us-west-2.compute.amazonaws.com
  become: yes
  tasks: 
    - name: Update package
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
    