---
- name: Install PostgreSQL
  hosts: ec2-35-88-142-250.us-west-2.compute.amazonaws.com
  become: yes
  tasks:
    - name: Install EPEL repo
      command: amazon-linux-extras install epel -y

    - name: Install necessary packages
      yum:
        name: ['postgresql96', 'postgresql96-server']
        state: present
        update_cache: yes

    - name: Initialize PostgreSQL
      command: /usr/bin/postgresql96-setup initdb

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql-9.6
        state: started
        enabled: yes