---
- name: Install PostgreSQL
  hosts: ec2-52-36-238-46.us-west-2.compute.amazonaws.com
  become: yes
  tasks:
    - name: Enable PostgreSQL Amazon Extras repository
      command: amazon-linux-extras enable postgresql10

    - name: Install necessary packages
      yum:
        name: ['postgresql', 'postgresql-server']
        state: present
        update_cache: yes

    - name: Find PostgreSQL setup script
      find:
        paths: "/"
        patterns: 'postgresql-*-setup'
        file_type: file
      register: setup_script

    - name: Initialize PostgreSQL
      command: "{{ setup_script.files[0].path }} initdb"

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes