---
- name: Postgre SQL Database installation and configuration
  hosts: ec2-35-88-142-250.us-west-2.compute.amazonaws.com
  become: true
  become_user: root
  tasks:
  - name: Get the OS platform
    command: cat /etc/os-release
    register: osRelease

  - name: Print the os-release
    debug: msg={{ osRelease.stdout }}

  - name: Update packages
    yum: name=* state=latest

  - name: Install PostgreSQL server
    yum:
      name: ['postgresql96', 'postgresql96-server']
      state: present

  - name: Check if Database is initialized
    stat:
      path: /var/lib/pgsql96/data/pg_hba.conf
    register: result

  - name: Initialize the database
    command: /usr/bin/postgresql96-setup initdb
    when: result.stat.exists == False

  - name: Ensure PostgreSQL service is running
    service:
      name: postgresql-9.6
      state: started
      enabled: yes