---
- name: Install PostgreSQL
  hosts: ec2-35-88-142-250.us-west-2.compute.amazonaws.com
  become: yes
  tasks:
    - name: Install necessary packages
      yum:
        name: ['postgresql', 'postgresql-server']
        state: present
        update_cache: yes

    - name: Initialize PostgreSQL
      command: service postgresql initdb

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes