---
- name: Install Apache on EC2
  hosts: 34.219.62.150
  become: yes
  tasks: 
    - name: Update package
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
    