---
- name: Install MySQL
  hosts: ec2-35-88-142-250.us-west-2.compute.amazonaws.com
  gather_facts: False
  become: yes
  tasks:
    - name: Ensure pip is installed
      yum:
        name: python3-pip
        state: present

    - name: Install PyMySQL
      pip:
        name: PyMySQL
        state: present

    - name: Update package
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install MySQL
      yum:
        name: mysql-server
        state: present
    - name: Start MySQL
      service:
        name: mysqld
        state: started
        enabled: yes
    - name: Create database
      community.mysql.mysql_db:
        name: mydb
        state: present

    - name: Create user
      community.mysql.mysql_user:
        name: myuser
        password: mypassword
        priv: 'mydb.*:ALL'
        state: present
