---
- name: Install Apache on EC2
  hosts: ec2-34-222-48-92.us-west-2.compute.amazonaws.com
  become: yes
  tasks: 
    - name: Update package
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Install necessary packages
      dnf:
        name: ['postgresql', 'postgresql-server']
        state: present
        update_cache: yes

    - name: Initialize PostgreSQL database
      command: postgresql-setup --initdb
      become_user: postgres

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Get PostgreSQL service status
      command: systemctl status postgresql.service
      register: service_status
      changed_when: false

    - name: Print PostgreSQL service status
      debug:
        msg: "{{ service_status.stdout_lines }}"