---
- hosts: localhost
  gather_facts: no
  vars:
    credential_name: "aap"
    inventory_name: "My Inventory"
    hosts:
      - name: "host1"
        ip: "172.34.2.0"
        group: "web"
      - name: "host2"
        ip: "192.168.1.1"
        group: "web"
      - name: "host3"
        ip: "192.168.255.0"
        group: "data"
  tasks:
    - name: Retrieve credential
      set_fact:
        credential: "{{ lookup('awx.awx.tower', 'credentials', query_params={'name': credential_name})[0] }}"

    - name: Create inventory
      uri:
        url: "{{ credential.inputs.url }}/api/v2/inventories/"
        method: POST
        user: "{{ credential.inputs.username }}"
        password: "{{ credential.inputs.password }}"
        force_basic_auth: yes
        body_format: json
        body:
          name: "{{ inventory_name }}"
          organization: 1
        status_code: 201
      register: inventory

    # Add the remaining tasks here, and include the user and password in each task