---
- hosts: localhost
  gather_facts: no
  vars:
    controller_url: "https://controller-443-ygqo5kmkth9i.env.play.instruqt.com/"
    inventory_name: "My Inventory"
    hosts:
      - name: "host1"
        ip: "172.34.2.0"
        group: "web"
      - name: "host2"
        ip: "192.168.1.1"
        group: "web"
      - name: "host3"
        ip: "192.168.255.0"
        group: "data"
  tasks:
    - name: Create inventory
      uri:
        url: "{{ controller_url }}/api/v2/inventories/"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
        body_format: json
        body:
          name: "{{ inventory_name }}"
          organization: 1
        status_code: 201
      register: inventory

    # Add the remaining tasks here, and include the Authorization header in each task