- hosts: localhost
  gather_facts: no
  tasks:
    - name: Find collections in ansible_collections
      find:
        paths: "/usr/share/ansible/collections/ansible_collections"
        file_type: directory
      register: collections

    - name: Print collections
      debug:
        var: collections.files