- hosts: awx
  gather_facts: no
  tasks:
    - name: Fetch AWX configuration file
      slurp:
        src: /etc/tower/settings.py
      register: awx_config

    - name: Print AWX configuration file
      debug:
        var: awx_config.content | b64decode