---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: List collections in ansible_collections
      shell: |
        for path in /usr/share/ansible/collections/*/*; do
          if [[ -d "$path" ]]; then
            echo "$path"
          fi
        done
      register: collections

    - debug: var=collections.stdout_lines