- hosts: aap
  gather_facts: no
  tasks:
    - name: Fetch AAP configuration file
      slurp:
        src: /etc/ansible/ansible.cfg
      register: aap_config

    - name: Print AAP configuration file
      debug:
        var: aap_config.content | b64decode