- hosts: localhost
  gather_facts: no
  tasks:
    - name: List collections
      command: ls -l /usr/share/ansible/collections/ansible_collections
      register: collections

    - name: Print collections
      debug:
        var: collections.stdout_lines