- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get list of collections
      command: ls /usr/share/ansible/collections/ansible_collections
      register: collections

    - name: Print collections
      debug:
        var: collections.stdout_lines

    - name: List sub-collections in collections
      command: ls -l /usr/share/ansible/collections/ansible_collections/{{ item }}
      loop: "{{ collections.stdout_lines }}"
      register: sub_collections
      ignore_errors: true

    - name: Print sub-collections
      debug:
        var: sub_collections.results