---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get collection paths
      shell: ansible-config dump | grep COLLECTIONS_PATHS | awk -F= '{print $2}' | tr -d '[:space:]' | tr ',' '\n'
      register: collection_paths

    - debug: var=collection_paths.stdout_lines

    - name: List collections in paths
      shell: |
        for path in {{ collection_paths.stdout_lines }}; do
          if [[ -d "$path" ]]; then
            find "$path" -type d -path '*ansible_collections/*/*'
          fi
        done
      register: collections

    - debug: var=collections.stdout_lines