---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get collection paths
      shell: ansible-config dump | grep COLLECTIONS_PATHS | awk -F= '{print $2}' | tr -d '[:space:]' | tr ',' '\n'
      register: collection_paths

    - name: List modules in collections
      shell: |
        for path in {{ collection_paths.stdout_lines }}; do
          if [[ -d "$path" ]]; then
            for collection in $(find "$path" -type d -name 'ansible_collections'); do
              collection_name=$(basename "$collection")
              ansible-doc -l -t module "$collection_name"
            done
          fi
        done
      register: modules

    - debug: var=modules.stdout_lines