---
- name: Get ServiceNow CI list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CI list from ServiceNow
      servicenow.itsm.configuration_item_info:
        sys_class_name: cmdb_ci_ip_address
      register: result

    - name: Extract skip_sync attribute
      set_fact:
        skip_sync_values: "{{ result.records | map(attribute='skip_sync') | list }}"

    - name: Print skip_sync values
      debug:
        var: skip_sync_values