---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Install awx.awx collection
      become: yes
      ansible.builtin.command: ansible-galaxy collection install awx.awx
    - name: Check if awx.awx collection is installed
      command: ansible-galaxy collection list
      register: output

    - name: Print message if awx.awx is installed
      debug:
        msg: "The awx.awx collection is installed."
      when: "output.stdout_lines | select('search', '^awx.awx') | list | length > 0"

    - name: Print message if awx.awx is not installed
      debug:
        msg: "The awx.awx collection is not installed."
      when: "output.stdout_lines | select('search', '^awx.awx') | list | length == 0"

    - name: Get list of collections in Ansible Automation Controller
      command: ansible-galaxy collection list
      register: controller_collections
