---
- name: Get ServiceNow CI list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CI list from ServiceNow
      servicenow.itsm.configuration_item_info:
        sys_class_name: cmdb_ci_ip_address
      register: result

    - name: Extract IP address attribute
      set_fact:
        ip_address_values: "{{ result.records | map(attribute='ip_address') | list }}"
    - name: debug value
      debug:
        var: ip_address_values