---
- name: Get ServiceNow CI list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CI list from ServiceNow
      servicenow.itsm.configuration_item_info:
        sys_class_name: cmdb_ci_ip_address
      register: result
      debug:
        var: result