---
- name: Get ServiceNow CI list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CI list from ServiceNow
      servicenow.itsm.configuration_item_info:
        sys_class_name: cmdb_ci_ip_address
      register: result

    - name: Extract IP address attribute
      set_fact:
        ip_address_values: "{{ result.records | map(attribute='ip_address') | list }}"

    - name: Create inventory
      set_fact:
        inventory: "{{ {'all': {'hosts': ip_address_values}} }}"

    - name: Write inventory to file
      copy:
        content: "{{ inventory | to_nice_yaml }}"
        dest: "/path/to/inventory.yml"

    - name: Print inventory
      debug:
        var: inventory
    - name: Add hosts to inventory in Ansible Automation Platform
      tower_host:
        name: "{{ item }}"
        inventory: "Demo Inventory"
        state: present
        tower_username: "admin"
        tower_password: "ansible123!"
        tower_host: "https://controller-443-jw4x7wxvoeiy.env.play.instruqt.com/"
      loop: "{{ ip_address_values }}"