---
- name: Get ServiceNow CI list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CI list from ServiceNow
      servicenow.itsm.configuration_item_info:
        instance: https://ansible.service-now.com
        username: qyf6ikt9y5ph
        password: qyf6ikt9y5ph
        query:
          sysparm_fields: ip_service_instance
      register: result

    - name: Print CI list
      debug:
        var: result