---
- name: Get ServiceNow CI list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CI list from ServiceNow
      servicenow.itsm.configuration_item_info:
         sys_class_name: cmdb_ci_ip_service_instance
        
      register: result

    - name: Print CI list
      debug:
        var: result